Update app.py
- Updated streamlit to work with new changes in harmonisation.py
NOTE: article = article_list[counter]
              ~~~~~~~~~~~~^^^^^^^^^
IndexError: list index out of range in researcher_node in harmonisation.py -> Need to debug the reason for occurrence